In [16]:
# file to mix pure state rhos into mixed states and save them as csvs
import numpy as np
from os.path import join, dirname, abspath
import pandas as pd
from tqdm import tqdm
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
import random

from uncertainties import ufloat
from uncertainties import unumpy as unp

from sample_rho import *
from lev.testing_experiment.rho_methods_1 import *
from process_expt_lev import *

DATA_PATH = 'mixed_phi_psi_45'
 # DEF GET THEO RHO

# DEF MIX RHO
    
def mix_states(file_names, probs, state_name):
    '''
    This returns mixed rhos and saves a csv with a mixed state.
    Note that uncertainity is taken as a mean, as is purity and fidelity.
    This file assumes one chi is being analyzed at a time.
    
    Parameters:
    file_names (list of lists): For N files, N lists of lists of the file names of each file,
                                organized in order of chi.
    probs (list): probability of the rho in each file.
    state_name (str): name of state to be used when saving data
    
    Returns:
    rhos (list): list of merged rhos
    '''
    
    # Obtain the data from each file, and use probs: 
    row_names = ['rho', 'unc', 'Su', 'un_proj', 'un_proj_unc', '_', 'angles', 'fidelity', 'purity']
    df = pd.DataFrame(index=row_names, columns=file_names) 
    for i, file in enumerate(file_names):
        data = np.load(join(DATA_PATH, file), allow_pickle=True)
        for j, row_name in enumerate(row_names):
            df.loc[row_name, file] = data[j]
        # Use probabilities on all values that I felt like
        df.loc['rho', file] = probs[i] * df.loc['rho', file]
        df.loc['unc', file] = probs[i] * df.loc['unc', file]
        df.loc['un_proj', file] = probs[i] * df.loc['un_proj', file]
        df.loc['un_proj_unc', file] = probs[i] * df.loc['un_proj_unc', file]
        df.loc['purity', file] = probs[i] * df.loc['purity', file]
        df.loc['fidelity', file] = probs[i] * df.loc['fidelity', file]
    # Create a new data frame and propagate it with previous data frames values
    df_to_save = pd.DataFrame(index = row_names)
    df_to_save['col'] = df[file_names[0]]
    for i, file_name in enumerate(file_names):
        if file_name == file_names[0]:  # Skip the first bc that is already in the new df
            pass
        else:
            df_to_save['col'] += df[file_name]
    
 
    # normalize the angle values

    rho, unc, Su, un_proj, un_proj_unc, state, angles, fidelity, purity = df_to_save.iloc[:, 0] 
    print(
    rho, unc, Su, un_proj, un_proj_unc, state, angles, fidelity, purity)
 
    np.save(join(DATA_PATH,f"rho_('E0', {state_name})_27"), df_to_save['col'].to_numpy())
    #save results
    #with open(f"int_state_sweep_phi45/rho_('E0', {state_n})_1.npy", 'wb') as f:
        #np.save(f, (rho, unc, Su, un_proj, un_proj_unc, state, angles, fidelity, purity))
    print(df.head(10))
    print(df_to_save.head(10))
    

# define experimental parameters
etas = [np.pi/4]
chis = np.linspace(0.001, np.pi/2, 6)
probs = [0.65, 0.35]
states_names = []
states = []

# define state names
for eta in etas:
    for chi in chis:
        states_names.append((np.rad2deg(eta), np.rad2deg(chi)))
        states.append((eta, chi))

# get new csvs of mixed state
for i, state_n in enumerate(states_names):
    filenames = []
    filenames.append(f"rho_('E0', {state_n})_1.npy")
    filenames.append(f"rho_('E0', {state_n})_26.npy")
    rad_angles = states[i]
    mix_states(filenames, probs, state_n)

ModuleNotFoundError: No module named 'lev'

In [6]:
data_old = np.load(join('mixed_phi_psi_45', "rho_('E0', (45.0, 0.057295779513082325))_26.npy"), allow_pickle=True)
print(data_old)

[array([[ 4.26651497e-03+0.j        , -8.25259095e-03+0.01553831j,
         -5.04200985e-03-0.00322539j, -4.80935521e-04-0.00160497j],
        [-8.25259095e-03-0.01553831j,  9.90044798e-01+0.j        ,
          2.30084847e-02+0.00243529j, -1.00228528e-02-0.01736127j],
        [-5.04200985e-03+0.00322539j,  2.30084847e-02-0.00243529j,
          2.91545190e-03+0.j        , -1.37218238e-03+0.00237476j],
        [-4.80935521e-04+0.00160497j, -1.00228528e-02+0.01736127j,
         -1.37218238e-03-0.00237476j,  2.77323473e-03+0.j        ]])
 array([[0.00171257+0.j        , 0.        +0.00276222j,
         0.        +0.00117779j, 0.        +0.00136139j],
        [0.        +0.00276222j, 0.00171257+0.j        ,
         0.        +0.00136139j, 0.        +0.00117779j],
        [0.        +0.00117779j, 0.        +0.00136139j,
         0.00171257+0.j        , 0.        +0.00276222j],
        [0.        +0.00136139j, 0.        +0.00117779j,
         0.        +0.00276222j, 0.00171257+0.j        ]]

In [15]:
data_new = np.load(join('mixed_phi_psi_45', "rho_('E0', (45.0, 0.057295779513082325))_27.npy"), allow_pickle=True)
print(data_new)

[array([[ 0.64425081+0.j        ,  0.02282622+0.00143428j,
         -0.01722696-0.02318644j, -0.00492507-0.00624597j],
        [ 0.02282622-0.00143428j,  0.34947644+0.j        ,
          0.00700124+0.00322147j, -0.0040076 -0.0061279j ],
        [-0.01722696+0.02318644j,  0.00700124-0.00322147j,
          0.00411782+0.j        ,  0.00078935+0.00103341j],
        [-0.00492507+0.00624597j, -0.0040076 +0.0061279j ,
          0.00078935-0.00103341j,  0.00215493+0.j        ]])
 array([[0.00226264+0.j        , 0.00096472+0.00096678j,
         0.00132857+0.00041223j, 0.        +0.00226021j],
        [0.00096472+0.00096678j, 0.00226264+0.j        ,
         0.        +0.00226021j, 0.00132857+0.00041223j],
        [0.00132857+0.00041223j, 0.        +0.00226021j,
         0.00226264+0.j        , 0.00096472+0.00096678j],
        [0.        +0.00226021j, 0.00132857+0.00041223j,
         0.00096472+0.00096678j, 0.00226264+0.j        ]])
 array([[0.        , 0.01261155, 0.0151787 , 0.00986438],
    

### Differences:
1. Everything is enclosed in an extra set of brackets.